---
apiVersion: v1
kind: Service
metadata:
  name: node
spec:
  type: LoadBalancer
  selector:
    app: node
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  labels:
    app: node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: prueba
        image: us-south1-docker.pkg.dev/GOOGLE_PROJECT/prueba/node:16