---
apiVersion: v1
kind: Namespace
metadata:
  name: tapp
---
apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: tapp
spec:
  type: LoadBalancer
  selector:
    app: node
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  namespace: tapp
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: cont-node
        image: us-east1-docker.pkg.dev/peinapp/tapp-demo/node:v1