name: Deploy NODE

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker $DOCKER_GCR_REPO_URL
        docker build -t $DOCKER_GCR_REPO_URL/$GOOGLE_PROJECT/tapp-demo/node:$GITHUB_SHA . 
        docker push $DOCKER_GCR_REPO_URL/$GOOGLE_PROJECT/tapp-demo/node:$GITHUB_SHA

    - name: deploy gke
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud container clusters get-credentials cluster-tapp-1 --zone=us-south1 --project $GCLOUD_PROJECT   
      # sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" resources.yaml
        kubectl apply -f resources.yaml
        kubectl set image deployment/$K8s_DEPLOYMENT_NAME $K8s_CONTAINER_NAME=$DOCKER_GCR_REPO_URL/$GCLOUD_PROJECT/node:$GITHUB_SHA
    
